spring:
  kafka:
    bootstrap-servers: localhost:19092
  data:
    redis:
      host: localhost
      port: 16379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
telcox:
  environment: dev
logging:
  level:
    root: INFO
    com.telcox: DEBUG
