sonar.projectKey=tamerakdeniz_telcox
sonar.organization=tamerakdeniz
sonar.projectName=telcox
sonar.sourceEncoding=UTF-8

sonar.sources=telco-common/src/main/java,telco-test-support/src/main/java,infrastructure,services,frontend/src
sonar.tests=telco-common/src/test/java,infrastructure/*/src/test/java,services/*/src/test/java
sonar.java.binaries=**/target/classes
sonar.java.test.binaries=**/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.exclusions=**/src/test/**,**/target/**,**/node_modules/**,frontend/dist/**,docker/**,k8s/**,infrastructure/keycloak/realm-export/**
sonar.test.inclusions=**/src/test/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
