apiVersion: v1
kind: ConfigMap
metadata:
  name: telcox-common-config
  namespace: telcox-local
  labels:
    app.kubernetes.io/name: telcox-common-config
    app.kubernetes.io/part-of: telcox-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_URL: "http://discovery-server:8761/eureka/"
  KAFKA_BOOTSTRAP: "kafka:29092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
  ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  LOGGING_STRUCTURED_FORMAT: "ecs"
  KEYCLOAK_ISSUER_URI: "http://localhost:18083/realms/telcox"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/telcox/protocol/openid-connect/certs"
  API_GATEWAY_URL: "http://api-gateway:8080"
  BFF_SERVICE_URL: "http://bff-service:9011"
  IDENTITY_SERVICE_URL: "http://identity-service:9001"
  CUSTOMER_SERVICE_URL: "http://customer-service:9002"
  PRODUCT_CATALOG_SERVICE_URL: "http://product-catalog-service:9003"
  ORDER_SERVICE_URL: "http://order-service:9004"
  SUBSCRIPTION_SERVICE_URL: "http://subscription-service:9005"
  USAGE_SERVICE_URL: "http://usage-service:9006"
  BILLING_SERVICE_URL: "http://billing-service:9007"
  PAYMENT_SERVICE_URL: "http://payment-service:9008"
  NOTIFICATION_SERVICE_URL: "http://notification-service:9009"
  TICKET_SERVICE_URL: "http://ticket-service:9010"
  BFF_DASHBOARD_CACHE_TTL: "45s"
  BFF_PLATFORM_CACHE_TTL: "15s"
  KAFKA_CONNECT_URL: "http://kafka-connect:8083"
  PROMETHEUS_URL: "http://prometheus:9090"
