apiVersion: v1
kind: Secret
metadata:
  name: telcox-local-secret
  namespace: telcox-local
  labels:
    app.kubernetes.io/name: telcox-local-secret
    app.kubernetes.io/part-of: telcox-platform
type: Opaque
stringData:
  DB_USER: "telcox"
  DB_PASSWORD: "telcox"
  JWT_SECRET: "telcox-local-dev-secret-key-please-change-in-production"
