server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18083/realms/telcox}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:18083/realms/telcox/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userOrIpKeyResolver}"
                redis-rate-limiter.replenishRate: ${RL_REPLENISH:20}
                redis-rate-limiter.burstCapacity: ${RL_BURST:40}
                redis-rate-limiter.requestedTokens: 1
          routes:
            - id: bff-service
              uri: http://bff-service:9011
              predicates: ["Path=/api/v1/bff/**"]
            - id: identity-service
              uri: http://identity-service:9001
              predicates: ["Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/identity/**"]
            - id: customer-service
              uri: http://customer-service:9002
              predicates: ["Path=/api/v1/customers,/api/v1/customers/**"]
            - id: product-catalog-service
              uri: http://product-catalog-service:9003
              predicates: ["Path=/api/v1/products,/api/v1/products/**,/api/v1/categories,/api/v1/categories/**,/api/v1/plans/**,/api/v1/tariffs/**,/api/v1/addons/**"]
            - id: order-service
              uri: http://order-service:9004
              predicates: ["Path=/api/v1/orders,/api/v1/orders/**"]
            - id: subscription-service
              uri: http://subscription-service:9005
              predicates: ["Path=/api/v1/subscriptions,/api/v1/subscriptions/**"]
            - id: usage-service
              uri: http://usage-service:9006
              predicates: ["Path=/api/v1/usage/**"]
            - id: billing-service
              uri: http://billing-service:9007
              predicates: ["Path=/api/v1/invoices,/api/v1/invoices/**,/api/v1/billing/**"]
            - id: payment-service
              uri: http://payment-service:9008
              predicates: ["Path=/api/v1/payments,/api/v1/payments/**"]
            - id: notification-service
              uri: http://notification-service:9009
              predicates: ["Path=/api/v1/notifications,/api/v1/notifications/**"]
            - id: ticket-service
              uri: http://ticket-service:9010
              predicates: ["Path=/api/v1/tickets,/api/v1/tickets/**"]
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}
telcox:
  gateway:
    cors:
      allowed-origins: ${GATEWAY_CORS_ORIGINS:http://localhost:5173,http://localhost:15173}
