server:
  port: 9011

telcox:
  bff:
    dashboard-cache-ttl: ${BFF_DASHBOARD_CACHE_TTL:45s}
    operation-ttl: ${BFF_OPERATION_TTL:30m}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
