telcox.profile: prod
telcox:
  bff:
    upstream:
      api-gateway: ${API_GATEWAY_URL:http://api-gateway:8080}
      bff-service: ${BFF_SERVICE_URL:http://bff-service:9011}
      identity-service: ${IDENTITY_SERVICE_URL:http://identity-service:9001}
      customer-service: ${CUSTOMER_SERVICE_URL:http://customer-service:9002}
      product-catalog-service: ${PRODUCT_CATALOG_SERVICE_URL:http://product-catalog-service:9003}
      order-service: ${ORDER_SERVICE_URL:http://order-service:9004}
      subscription-service: ${SUBSCRIPTION_SERVICE_URL:http://subscription-service:9005}
      usage-service: ${USAGE_SERVICE_URL:http://usage-service:9006}
      billing-service: ${BILLING_SERVICE_URL:http://billing-service:9007}
      payment-service: ${PAYMENT_SERVICE_URL:http://payment-service:9008}
      notification-service: ${NOTIFICATION_SERVICE_URL:http://notification-service:9009}
      ticket-service: ${TICKET_SERVICE_URL:http://ticket-service:9010}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
